name: build-image

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 1 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kali-base
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image reference
        id: meta
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "image=${{ env.REGISTRY }}/${OWNER}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          podman info
          podman build -t ${{ steps.meta.outputs.image }} .

      - name: Push image
        if: github.event_name != 'pull_request'
        run: |
          podman push ${{ steps.meta.outputs.image }}
